### PR TITLE
chore: adjust tabs across app & remove contract unused tabs

### PR DESCRIPTION
**Pull request by pedronauck**
⭐ Closes FE-28
⭐ Closes FE-30
⭐ Closes FE-46
⭐ Closes FE-41

### CODE REVIEW

**Review by luizstacio — CHANGES_REQUESTED** [review]
The tabs should look like the following but I don't see the changes they look like buttons yet.
Screenshot 2023-11-09 at 2 49 06 PM

**Comment by pedronauck** [comment]
> The tabs should look like the following but I don't see the changes they look like buttons yet. Screenshot 2023-11-09 at 2 49 06 PM

I just followed [what we have on Figma](https://www.figma.com/file/VTWcuPxsUtKZDk0iKn3y7T/Fuel-Portal-Product-Board?type=design&node-id=2121-35623&mode=design&t=GYs7v7aYIRfkbwhA-4) dude

**Comment by LuizAsFight** [comment]
we talked to use button style in our sync meeting... but I also prefer the contract tab style

cc @pedronauck @luizstacio

**Review by luizstacio — CHANGES_REQUESTED** [review]
I found two more things here:
1. Minor one is the margin between the line in the top and the tabs.
Screenshot 2023-11-15 at 6 09 48 PM

2. On this version if you navigate to a tab and click to return on the browser, the content changes but the tabs not. Testing on the master version this issue not exists.

**Review by luizstacio — APPROVED** [review]

**Pull request merged**
