### PR TITLE
fix: predicate tab not disabled for accounts

### PR DESCRIPTION
**Pull request by xlzy905**
Issuse: https://github.com/FuelLabs/fuel-explorer/issues/454

Problem: The account will return a '0x' string
image

### CODE REVIEW

**Review by arthurgeron — CHANGES_REQUESTED** [review]
CLA must be signed

**Comment by xlzy905** [comment]
> CLA must be signed

 @arthurgeron CLA has been signed. Please check

**Comment by arthurgeron** [comment]
Your changes are missing from this PR @xlzy905

**Comment by xlzy905** [comment]
> Your changes are missing from this PR @xlzy905

 have submitted again. @arthurgeron

**Review by arthurgeron — APPROVED** [review]
LGTM . We only need the failing e2e test to be tweaked around your changes.

**Review by arthurgeron — CHANGES_REQUESTED** [review]
E2E needs some adjustments

**Comment by arthurgeron** [comment]
Closing this as it got fixed in our GraphQL resolutions. We appreciate your contribution.

**Pull request closed without merging**
