### PR TITLE
fix: preventing 0x predicates to being showed and persisted

### PR DESCRIPTION
**Pull request by rodrigobranas**
- Closes: #454 

Screenshot 2024-09-09 at 11 30 30
Screenshot 2024-09-09 at 11 30 44
Screenshot 2024-09-09 at 11 30 20

### CODE REVIEW

**Review by helciofranco — APPROVED** [review]

**Review by arthurgeron — CHANGES_REQUESTED** [review]
I think E2E tests expected predicate tabs to always show, they probably need to be adjusted

**Comment by arthurgeron** [comment]
This PR overlaps with #458. Though imho adjusting directly in graphql resolve seems like a better solution.

**Comment by rodrigobranas** [comment]
> I think E2E tests expected predicate tabs to always show, they probably need to be adjusted

actually there are different issues, I was indexing 0x predicates and this PR is preventing that for next blocks. For the existing blocks I'm just avoiding return 0x predicates as it's not valid and makes sense while I don't delete them from database.

About the E2E tests, I did not change the behavior of the frontend, just not returning when there is no predicate (considering 0x).

**Comment by rodrigobranas** [comment]
> This PR overlaps with #458. Though imho adjusting directly in graphql resolve seems like a better solution.

I think that does not make sense to handle that on the frontend, it needs to rely on the backend in order to know whether there is or there isn't predicate for the account

**Review by arthurgeron — APPROVED** [review]

**Pull request merged**
