### PR TITLE
fix: themes not returning correctly

### PR DESCRIPTION
**Pull request by matt-user**
closes FE-87

### CODE REVIEW

**Comment by matt-user** [comment]
for some reason `updateThemeAppearanceClass` does not update `useThemeContext` so `useThemeContext` would always return dark.

**Review by pedronauck — CHANGES_REQUESTED** [review]
When reloading using network with no cache and fast 3g it's happening this...

CleanShot 2024-02-01 at 19 44 34@2x

**Review by luizstacio — CHANGES_REQUESTED** [review]
With the new implementation the theme configuration is lost on every refresh.

**Comment by matt-user** [comment]
> With the new implementation the theme configuration is lost on every refresh.

@luizstacio if you are referring to the tx screen this happens on main too.  I'll investigate the issue and fix it in this pr.

**Comment by luizstacio** [comment]
> > With the new implementation the theme configuration is lost on every refresh.
> 
> @luizstacio if you are referring to the tx screen this happens on main too. I'll investigate the issue and fix it in this pr.

@matt-user yeah this is true, I didn't notice that before. Last merge this PR and fix in another task.

**Review by luizstacio — APPROVED** [review]

**Review by pedronauck — APPROVED** [review]

**Pull request merged**
