### PR TITLE
feat: upgrade radix themes to v3

### LINKED ISSUE #355: Apply changes to design system
- Apply changes from figma to our design system

Review and create doc for:
- Things that are not looking good
- Things that are not possible to apply on radix theme

### PR DESCRIPTION
**Pull request by arthurgeron**
Fixes #355 and #354 

## Description
We aim for cleaner, more maintainable code. With that in mind, we aimed to move torwards a more purist use of Radix UI Theme components, with as little overriding as possible.
This PR aims to bring the new color system tokens, adapted to the Radix UI Color System & Color Palettes on V3.

## Features
- Radix Migrated to V3 
- `tailwindcss-radix` updated to V3
- Removed most of CSS overrides on Radix UI's components
- Fixed typing and linting issues with the new Radix V3 components
- Refactored `radix-ui-themes-with-tailwind@1.2.6` to work with Radix V3, which now lives in `@fuels/ui`
- Refactored InputAmount and Input components to accomodate V3 breaking changes
- Added Tooltip variants to StoryBook
- Added Alert variants to StoryBook
- Removed Radix UI packages that are no longer used 

## Fixes
-  Removed border and text color tailwind classes clashing with Radix's Design
- Storybook not parsing `node:` urls 
- Crash in Explorer's `AccountTabs` story when trying to read NextJS's current route pathname
- Vertically misaligned `Checkbox` text
- ComboBox:
  - Now opens/closes with `Enter`
  - Added pointer cursor to dropdown items
  - Pop over not closing when clicking outside
- Misalignments in Switch component
- Allow `TextArea` component to be resized
- Confusing wording in `Context Menu`'s Story
- Dialog Title and general stile issues
- Breadcrumb icons & text misalignment
- Tabs design and behavior in Radix V3
- State selectors [refactored](https://github.com/FuelLabs/fuel-explorer/pull/358/commits/286b5ec29c546f610623a6801f04758661d9500e) to work with Radix V3 syntax

## Breaking Changes
- Replaced Toggle Group with Radix UI's Segmented Control
- Radix V3 introduces a new color system and has many breaking changes, I recommend reading the [Radix V3 Migration Guide](https://www.radix-ui.com/themes/docs/overview/releases#upgrade-guide)
- `width` and `height` props no longer directly accept space values (e.g. `9`, `8`), they can still be referenced directly via `var(--space-9)` but they won't scale to screen. For more info check the [migration guide](https://www.radix-ui.com/themes/docs/overview/releases#upgrade-guide)
- Radix components no longer accept any string in the `as` prop, now the accepted values are `div` and `span`
- Tailwind radix state selectors are now `data-[state=selector]:` instead of `state-selector`
- Input:
  - `Input.Field` has been merged to `Input.Root`, for mor details click here
  - `Input.Number` removed due to Radix V3 changes to the Input component
  - Default stylings have been updated to work with Radix V3. Check our StoryBook for examples.
  - `Slots` can now be placed, horizontally, by changing the `side` prop to `"left"` or `"right"`
- InputAmount:
  -  Uses Input component as a base, so it has also carries the breaking changes from the latter
  - InputAmount.Field removed due to Radix V3 changes to the Input component
- `grow` or `shrink` props renamed to `flexGrow` and `flexShrink` respectively.
- `width` and `height` props no longer scale to space.
- Removed the following is a list of all CSS variables and Radix UI overrides that have been removed:
```
accent-10
accent-9-contrast
accent-9
inverse-a10
inverse-a11
inverse-a12
inverse-a1
inverse-a2
inverse-a3
inverse-a4
inverse-a5
inverse-a6
inverse-a7
inverse-a8
inverse-a9
inverse
```

### CODE REVIEW

**Comment by arthurgeron** [comment]
@pedronauck @LuizAsFight @helciofranco might want to select some semantic color variables to maintain (e.g. success, error), we just need to decide which color tokens they're going to be.

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
Header before / after
image
/
image

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
before / after
image
/
image

1- tab broken
2- can we keep same color ratio as before? it was grayer now its whiter. also check this ratio in other screens

**Review by LuizAsFight — COMMENTED** [review]
image

- outputs arrow should be green

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
image

internal border should be the same as external (now it's white)

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
before/after
image

/

image


can we make the description be same color of the link ?

**Comment by arthurgeron** [comment]
> it was grayer now its white
That's because radix generally uses gray-12 color step for fonts. I was waiting on Kevin to see if he would make changesto the gray color palette. 
For now I will just use a default text color var exposed tailwind and apply it to those components.

**Comment by arthurgeron** [comment]
@LuizAsFight  I've fixed the mentioned issues. 
I've restored the old CSS variables references, using the new color palettes (PR description updated)

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
